spring.application.name: OAuth2ResourceDemo
server.port: 7070
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/SpringBootKeyCloakApp/
jwkSetUri: http://localhost:8080/realms/SpringBootKeyCloakApp/protocol/openid-connect/certs